### PR TITLE
chore: move build-js-sdk to public

### PR DESCRIPTION
**Pull request by andrewwylde**

### CODE REVIEW

**Review by saisatishkarra — APPROVED** [review]
gtm

**Comment by saisatishkarra** [comment]
merge as required and create a new tag. Once all the check on the server tag passes, update `v1` to latest semver tag

**Comment by saisatishkarra** [comment]
Please add a test workflow and dependabot config for this action to make sure it is not broken on new tags  and pr's for dependency updates so it doesn't affect downstream apps and is caught early!!

**Comment by saisatishkarra** [comment]
> @saisatishkarra do I need to do anything about the Test Scan Docker Image failing to log in?

Not needed. It is failing because of missing credentials on the fork. I will fix this check but it should run fine when merged to main / any tag creation.

**Review by saisatishkarra — CHANGES_REQUESTED** [review]
please add test workflow and dependabot config

**Comment by andrewwylde** [comment]
OK, thanks for the advice, @saisatishkarra ! I went ahead and moved all of the checkout logic (and any directory-dependent logic) to action inputs, so we should be good to go!

**Review by saisatishkarra — APPROVED** [review]
gtm

**Comment by saisatishkarra** [comment]
@andrewwylde  thanks for the changes. you can go ahead and get this merged and create a tag / release.

**Pull request merged**
